export class ServantModel {
  id: number;
  collectionNo: number;
  name: string;
  ruby: string;
  className: string;
  type: string
  flag: string
  rarity: number
  cost: number
  lvMax: number
  extraAssets: any
  gender: string
  attribute: string
  traits: any[]
  starAbsorb: number
  starGen: number
  instantDeathChance: number
  cards: any[]
  hitsDistribution: any
  cardDetails: any
  atkBase: number
  atkMax: number
  hpBase: number
  hpMax: number
  relateQuestIds: number[]
  growthCurve: number
  atkGrowth: number[]
  hpGrowth: number[]
  bondGrowth: number[]
  expGrowth: number[]
  expFeed: number[]
  bondEquip: number
  valentineEquip: number[]
  valentineScript: any[]
  bondEquipOwner: number
  valentineEquipOwner: number
  ascensionAdd: any
  traitAdd: any[]
  svtChange: any[]
  ascensionMaterials: any
  skillMaterials: any
  appendSkillMaterials: any
  costumeMaterials: any
  coin: any
  script: any
  skills: any[]
  classPassive: any[]
  extraPassive: any[]
  appendPassive: any[]
  noblePhantasms: any[]
  profile: any
}
